// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

// Program otelcol-dev is an OpenTelemetry Collector binary.
package main

import (
	"log"
	// "net/http"
	// _ "net/http/pprof"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/otelcol"
)

func main() {
	// PPROF INJECTION
	// go func() {
	// 	log.Println(http.ListenAndServe("localhost:6060", nil))
	// }()
	info := component.BuildInfo{
		Command:     "otelcol-dev",
		Description: "Basic OTel Collector distribution for Developers",
		Version:     "1.0.0",
	}

	if err := run(otelcol.CollectorSettings{BuildInfo: info, Factories: components}); err != nil {
		log.Fatal(err)
	}
}

func runInteractive(params otelcol.CollectorSettings) error {
	cmd := otelcol.NewCommand(params)
	if err := cmd.Execute(); err != nil {
		log.Fatalf("collector server run finished with error: %v", err)
	}

	return nil
}
