name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Generate Tag for Current Date
        id: generate_tag
        run: |
          TAG=$(date +'%Y%m%d')
          echo "Generated tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/otel-compressor:${{ env.TAG }} ./otel-compressor
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/otel-compressor:${{ env.TAG }}
